Fix Attributes naming + update changelog
astarte-platform/astarte-go pull request #22
Opened 2021-03-23 10:09 UTC by matt-mazzucato

- When dealing with a single device attribute use the singular. Use the plural otherwise.
- Update the changelog.

2021-03-23 10:15 UTC, rbino requested changes

2021-03-23 10:15 UTC, rbino commented on client/appengine_devices.go
> +func (s *AppEngineService) SetDeviceAttribute(realm, deviceIdentifier string, deviceIdentifierType DeviceIdentifierType, attributesKey, attributesValue string) error {
`attributesKey` -> `attributeKey`
`attributesValue` -> `attributeValue`

2021-03-23 10:15 UTC, rbino commented on client/appengine_devices.go
> +func (s *AppEngineService) DeleteDeviceAttribute(realm, deviceIdentifier string, deviceIdentifierType DeviceIdentifierType, attributesKey string) error {
`attributesKey` -> `attributeKey`

2021-03-24 15:56 UTC, bettio approved these changes

2021-03-24 15:56 UTC, merged