Interfaces: add validations for required fields
astarte-platform/astarte-go pull request #25
Opened 2022-03-28 08:59 UTC by matt-mazzucato

When parsing an Astarte interface, ensure that required fields are valid.

2022-03-28 09:52 UTC, Annopaolo approved these changes

2022-03-28 15:07 UTC, rbino approved these changes

2022-03-28 16:31 UTC, rbino requested changes

2022-03-28 16:34 UTC, matt-mazzucato commented on interfaces/astarte_interface.go
> +	}
The future me thanks you! :)

2022-03-31 09:20 UTC, Annopaolo requested changes

2022-03-31 09:20 UTC, Annopaolo commented on interfaces/astarte_interface.go
> +}
Type and ownership should be required, too (see [the docs](https://docs.astarte-platform.org/latest/040-interface_schema.html#interface)).

2022-03-31 11:10 UTC, Annopaolo approved these changes

2022-04-04 11:35 UTC, bettio approved these changes

2022-04-04 11:36 UTC, bettio approved these changes

2022-04-04 11:36 UTC, merged